name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - ian_testing

jobs:
  build-and-push:
    permissions:
      id-token: write
      attestations: write
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build Image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Attest Provenance
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cosign
        run: |
          curl -LO https://github.com/sigstore/cosign/releases/download/v1.4.0/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign

      - name: Verify Image
        run: |
          cosign verify ghcr.io/liatrio/tag-automated-governance-github-attestations-beta \
            --payload=ghcr.io/liatrio/tag-automated-governance-github-attestations-beta@sha256:9801e0612ebd6349136b9b34a8b154f508f26d41c0054a0d6d2e0cafb5889f38 \
            --certificate-identity=https://github.com/liatrio/tag-automated-governance-github-attestations-beta/.github/workflows/build.yaml@refs/heads/main \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com
